name: Add/Update Event Request
description: Request an open-source event to be added to the atlas
title: "[EVENT]: "
labels: ["event-data"]
body:
  - type: textarea
    id: description
    attributes:
      label: Event Details
      description: Provide the details of the event you'd like to add or update.
    validations:
      required: true
